EBI-G2P/gene2phenotype_app

templates/header.html.ep
=> add survey banner

lib/Gene2phenotype/Controller/Login.pm
Check if email is registered before sending email to recover password.
=> Recover password - check if email is registered

lib/Gene2phenotype/Model/GenomicFeatureDisease.pm, templates/gfd.html.ep, templates/user/gfd.html.ep
Description: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4265
=> Adding the new flag to the G2P website

templates/terminology.html.ep
=> Adding the new terminology, tested

public/gene2phenotype/README
=> Updating the README to show the added colunms

public/gene2phenotype/README, templates/updates_to_our_terms.html.ep
=> Changes to the templates and README

templates/about.html.ep
=> Adding publications to the about page

templates/g2p_vep_plugin.html.ep
Changing the documentation https://www.ebi.ac.uk/gene2phenotype/g2p_vep_plugin adding the new terminology information.
=> Changing documentation of the VEP_G2P_plugin documents

lib/Gene2phenotype/Model/GenomicFeatureDisease.pm, templates/gfd.html.ep, templates/user/gfd.html.ep
[ENSVAR-4750](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4750)
=> Views for variant consequences

lib/Gene2phenotype/Model/Disease.pm, templates/disease.html.ep
[ENSVAR-4684](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4684)
=> Disease ontology view

templates/header.html.ep, templates/terminology.html.ep, templates/updates_to_our_terms.html.ep
[ENSVAR-4795](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4795)
=> Changes to the documentation

templates/about.html.ep, templates/gfd.html.ep, templates/terminology.html.ep, templates/user/gfd.html.ep
Changes to support request about more curation information.
=> Changes to support more information

templates/downloads.html.ep, templates/updates_to_our_terms.html.ep
[ENSVAR-4959](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4959)
=> Adding the FTPsite to our download page

templates/phenotype.html.ep, templates/user/phenotype.html.ep
=> Update phenotypes display

templates/about.html.ep
> Adding new curators
> Adding information on how to be cited
=> The about page

public/gene2phenotype/README, templates/terminology.html.ep, templates/updates_to_our_terms.html.ep
Should be merged after https://github.com/EBI-G2P/ensembl-gene2phenotype/pull/74
=> Changes to the website to support removal of both RD and IF 

lib/Gene2phenotype/Controller/GenomicFeatureDisease.pm, lib/Gene2phenotype/Controller/GenomicFeatureDiseasePanel.pm, lib/Gene2phenotype/Model/GenomicFeatureDisease.pm, templates/add_new_entry.html.ep
[ENSVAR-5131](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5131)
=> G2P website- Adding variant consequence entry

public/gene2phenotype/README, templates/terminology.html.ep, templates/updates_to_our_terms.html.ep
[ENSVAR-5285](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5285)
[ENSVAR-5289](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5289)
=> Updating docs new attribs

templates/g2p_vep_plugin.html.ep
[ENSVAR-3959](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3959)
=> Changes to the plugin documentation to support new option

templates/about.html.ep
[ENSVAR-5746](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5746)
=> Adding cardiac and changing eye paper

lib/Gene2phenotype/Controller/Search.pm, templates/user/searchresults.html.ep
QUICK FIX https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=666149
=> Changes to the search results

lib/Gene2phenotype/Controller/GenomicFeatureDiseaseComment.pm, lib/Gene2phenotype/Model/GenomicFeatureDiseaseComment.pm, templates/user/comments.html.ep
[ENSVAR-5769](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5769)
=> Public and private comments addition

lib/Gene2phenotype/Controller/Search.pm, lib/Gene2phenotype/Model/Search.pm
[ENSVAR-5893](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5893)
This PR requires the following update: https://github.com/EBI-G2P/ensembl-gene2phenotype/pull/84
Search by phenotypes:
- when we search by disease then also search by phenotype name
- if there is no result by disease then does a separate phenotype search
=> Support search by phenotype

templates/g2p_vep_plugin.html.ep
Update default confidence values in the docs.
[ENSVAR-5555](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5555)
=> Update vep plugins docs

public/gene2phenotype/scripts/behavior.js
https://www.ebi.ac.uk/panda/jira/browse/G2P-2
=> Updating Neonatal

lib/Gene2phenotype/Model/Search.pm
To test search by: `NEUROFIBROMATOSIS`
[ENSVAR-5944](https://www.ebi.ac.uk/panda/jira/browse/)
=> Remove duplicated results when searching by term

lib/Gene2phenotype/Controller/GenomicFeatureDiseasePanel.pm, lib/Gene2phenotype/Model/Disease.pm, lib/Gene2phenotype/Model/GenomicFeatureDisease.pm, lib/Gene2phenotype/Model/GenomicFeatureDiseasePublication.pm, public/gene2phenotype/scripts/alerts.js, templates/add_new_entry.html.ep
[ENSVAR-5296](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5296)
=> Adding PMID and MONDO on creating new entry 

templates/terminology.html.ep
https://www.ebi.ac.uk/panda/jira/browse/G2P-8
=> Changes to the typo in the terminology documentation

cpanfile
Adding the new module required for the setup.
=> Adding the module to the cpanfile

templates/login/login.html.ep
In login page, display alert when incorrect username or password is entered
=> Display alert in login page

lib/Gene2phenotype/Model/Search.pm
Search returns an error when searching for "Rod-cone dystrophy":
https://www.ebi.ac.uk/gene2phenotype/search?panel=ALL&search_term=Rod-cone+dystrophy
=> Fix search

templates/about.html.ep
Details: [G2P-100](https://www.ebi.ac.uk/panda/jira/browse/G2P-100)
=> Add preprint

templates/header.html.ep, templates/survey_services.html.ep
[G2P-153](https://www.ebi.ac.uk/panda/jira/browse/G2P-153)
=> Adding the survey link using the ensembl template

templates/phenotype.html.ep, templates/user/phenotype.html.ep
[G2P-156](https://www.ebi.ac.uk/panda/jira/browse/G2P-156)
=> Changing the link

templates/about.html.ep
[G2P-192](https://www.ebi.ac.uk/panda/jira/browse/G2P-192)
=> Updating the about page

lib/Gene2phenotype.pm, templates/downloads.html.ep
=> Fix download for hearing loss panel name

templates/header.html.ep, templates/header_no.html.ep, templates/login/login.html.ep
This PR contains the following changes:
1. Remove sign in button in header
2. On login page, remove login form and display info banner
=> Remove sign in button and login form and display info banner

templates/updates.html.ep
Code changes related to [G2P-462](https://www.ebi.ac.uk/panda/jira/browse/G2P-462). Update site switchover notice banner text on homepage.
=> G2P-462 - Update site switchover notice banner text on homepage

templates/header.html.ep, templates/header_no.html.ep, templates/login/login.html.ep, templates/updates.html.ep
Follow up code changes related to [G2P-462](https://www.ebi.ac.uk/panda/jira/browse/G2P-462).Display site switchover notice banner on header and remove banner on homepage and login page.
=> G2P-462 - Display site switchover notice banner on header and remove banner on homepage and login page
